### ISSUE TITLE
Got some error while develop next js web app

### ISSUE THREAD

**Issue by kfnx** [egoist/logbox#4]
Im not sure is it my issue or logbox issue, but maybe it could help logbox development.
I got this error while developing my web app (next js app). For around 15 minutes logbox works properly then there is an error saying its from chrome extension. the error dissapeared after i disabled logbox extension

<img width="490" alt="Screenshot 2020-08-21 at 10 51 09" src="https://user-images.githubusercontent.com/33047308/90851032-aec8fe80-e39d-11ea-9477-001b215ebc6e.png">

**Comment by egoist** [comment]
Should be fixed in `master` branch
